GOROOT := /Users/pgm/dev/go
PATH := $(GOROOT)/bin:$(PATH)

include $(GOROOT)/src/Make.inc

TARG=gospoke

GOFILES=\
	timeline.go\
	heartbeat.go\
	endpoint.go\
	service.go\
	executor.go\
	main.go

include $(GOROOT)/src/Make.cmd
